<FloatLayout>:
    Button:
        text: "Top/Left"
        pos_hint: {'x': 0, 'top': 1}
        size_hint: (None, None)
        size: (75, 75)
    Button:
        text: "Bottom/Right"
        pos_hint: {'right': 1, 'y': 0} 
        size_hint: (None, None)
        size: (75, 75)

    Button:
        text: "Middle"
        pos_hint: {'center_x': 0.5, 'center_y': 0.5} 
        size_hint: (None, None)
        size: (75, 75)