<GridLayout>:
    cols: 4
    rows: 4
    Button:
        text: "Black"
        size: (75, 75)
    Label:
        text: "White"
        size: (75, 75)
    Button:
        text: "Black"
        size: (75, 75)
    Label:
        text: "White"
        size: (75, 75)
    Label:
        text: "White"
        size: (75, 75)
    Button:
        text: "Black"
        size: (75, 75)
    Label:
        text: "White"
        size: (75, 75)
    Button:
        text: "Black"
        size: (75, 75)

