<MyPageLayout>:
    Button:
        text: "Page 1"
        font_size: "48dp"
        color: (1, 0, 0, 0.8)
        bold: True
        font_name: "fonts/LCD.ttf"
    Button:
        text: "Page 2"
        font_size: "48dp"
        on_press: root.print_hola()
        
    Button:
        text: "[color=ff3333]Hello[/color][color=3333ff]World[/color]"
        markup: True
        font_size: "96dp"
        
    
