<StackLayout>:
    orientation: "rl-bt"

    Button:
        text: "A"
        size_hint: (None, None)
        size: (75, 75)
    Button:
        text: "B"
        size_hint: (None, None)
        size: (75, 75)
    Button:
        text: "C"
        size_hint: (None, None)
        size: (75, 75)
    Button:
        text: "D"
        size_hint: (None, None)
        size: (75, 75)
    Button:
        text: "Efe"
        size_hint: (None, None)
        size: (75, 75)