<StackLayout>:
    Button:
        text: "A"
        size_hint: (None, None)
    Button:
        text: "B"
        size_hint: (None, None)
        size: (275, 75)
    Button:
        text: "C"
        size_hint: (None, None)
        size: (275, 75)
    Button:
        text: "D"
        size_hint: (None, None)
        size: (275, 75)
    Button:
        text: "Efe"
        size_hint: (None, None)
        size: (275, 75)