# Generated by Django 3.1.1 on 2021-05-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cuartel', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metahumano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('identidad', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='metahumans.equipo')),
                ('poderes', models.ManyToManyField(to='metahumans.Poder')),
            ],
        ),
    ]
