# Generated by Django 3.0.5 on 2020-05-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0003_metahuman'),
    ]

    operations = [
        migrations.AddField(
            model_name='metahuman',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
