# Generated by Django 3.0.5 on 2020-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0004_metahuman_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(max_length=4000)),
                ('headquarter', models.CharField(max_length=100)),
            ],
        ),
    ]
