# Generated by Django 3.0.5 on 2020-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metahumans', '0006_auto_20200504_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metahuman',
            name='country',
            field=models.CharField(choices=[('US', 'United states'), ('ES', 'Spain'), ('UK', 'United Kingdom'), ('PL', 'Polonia'), ('OT', 'Others')], max_length=2),
        ),
    ]
